language: objective-c
before_install:
  - gem install cocoapods
  - gem install xcpretty
script: xcodebuild -project  -scheme 'ArsDashFunction' -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES
  clean build test | xcpretty -c
